### ISSUE TITLE
Can we help you update the mod?

### ISSUE THREAD

**Issue by Grey-97** [TheMegafuji/MegaAethric#14]
I mean do we have the right....? If so, I know how to program but I have never worked with decompiled apks, I have seen your work on "app-3ed96eacc7e587045f23.js".... But I'm not sure if just putting in new code and merge it would be enough or I would need to look at more things besides that file. I can always use trial and error but I'd like to save my time haha.

**Comment by phreakyness** [comment]
If you get an update going, wanna share it? I'd love see this mod continued with but the creator seems to be doing other stuff for now :(

**Comment by Matvel007** [comment]
> If you get an update going, wanna share it? I'd love see this mod continued with but the creator seems to be doing other stuff for now :(

most likely so

**Comment by Axibed** [comment]
> sure, I'm new to this but there is a lot of work to do, there have been a lot of updates and a lot of things to look at, I'd say I have 1/3 of the work done... Some files are huge and muy pc crashed a few times lol... I only have free time on Sunday and I can't guarantee that all the scripts will work but for now I will continue with the challenge.

Dude, let's wait, good luck to you

**Comment by TheMegafuji** [comment]
Hey @Grey-97 and everyone, I didn't update the bot yet because I have been very very busy. For anyone who wants to contribute with the new version, first getting the latest APK (from the official store), use [apktool](https://github.com/iBotPeaches/Apktool) to decompile the apk, inside the assets folder will be a app-randomstring.js
this is the main file and the one you need to look up into.
I've updated the app twice, the first one was in another repo, this repo has two of the updates, if you check the commits (problably [3f17cda](https://github.com/TheMegafuji/MegaAethric/commit/3f17cda62617e617f384702c2eb4669bd8f3959f)) will have most of the updates, since its a pain in the ass to update, I left a comment //MEGA: at the top of each section.
The commit [86fbd23](https://github.com/TheMegafuji/MegaAethric/commit/86fbd234d2891a452cf4d3e81fc2a039cb2a8140) is basically the code formated with very few additions, if you use vcs tools you can compare the current code with that commit's code and see the difference, perhaps there might be some pieces of code I missed the comment.

Some variables will change, because it runs through a obfuscator and it always do different results and variable names.

@Grey-97 you said the logic has changed, try loading the html in your PC and with devtools inspect the element and try sending console js commands to achieve the click, its certainly not fully protected, there are several ways to simulate click, I'll list some:

1. `element.click()`
2. Creating and dispatching MouseEvent (TouchEvents as well)
```javascript
const event = new MouseEvent('click', { //here you can change to mouseUp, down, touchDown, etc..
  bubbles: true,
  cancelable: true,
  view: window
});
element.dispatchEvent(event);
```
3. Triggering a click event using dispatchEvent (it basically does the same as the first, but who knows)
```javascript
const event = document.createEvent('HTMLEvents');
event.initEvent('click', true, false);
element.dispatchEvent(event);
```
4. `Element.prototype.click.apply(element);`

sure you can find plenty more, there are also a few examples in the code probably

**Comment by Xray1716** [comment]
I can't wait for the bot update. It would be nice if the bot could not only attack and use the magic of 1 slot, but also some spells and their sequence. Although I think it's not that easy. It's not artificial intelligence. But in any case, we all the community will be glad to see the release of a new version of the bot Mega Aethric! ❤

**Comment by Axibed** [comment]
> I have spent too much time on this haha... I have removed a lot of things because... I'll be honest, I was lazy haha. Sorry @TheMegafuji for not having it in one piece but with so many updates I have kept it as short as possible. Still need to figure it out how to compile back to apk,
> 
> what I did is: 1 apktool b gamefolder 2 jarsigner -keystore aethric.keystore -verbose name.apk mega 3 apksigner sign --ks .\aethric.keystore name.apk but I still can't install it on my android not sure why
> 
> But anyway I enjoyed the experience with js (I miss python) v1.1.27 [https://mega.nz/file/lIUGUS5I#gFhF2AyP1MVpkeYP2_lgLUm0y6inYX0wd7zcWNedPbg](url)

Bro, The link is invalid

**Comment by TheMegafuji** [comment]
I have setted up a tutorial in readme for generating the apk, have you tried it?

**Comment by Sfdlss** [comment]
i decompiled this using apktool, so far it's working fine, but i haven't tried all the features
Try it yourself

https://mega.nz/file/yH5U1biZ#LOk7CxgRn7S4DXVgB1y82WjK_a6lMDjt3VqQ_AyfHzU

**Comment by Axibed** [comment]
> i decompiled this using apktool m, so far it's working fine, but i haven't tried all the features Try it yourself
> 
> https://mega.nz/file/yH5U1biZ#LOk7CxgRn7S4DXVgB1y82WjK_a6lMDjt3VqQ_AyfHzU
> 
> I cant find codex hack, its removed?

Yes, the add mobs to white-list in codex button is gone

**Comment by Sfdlss** [comment]
Be careful everyone, my account got disabled when using new version of this mod

Its safer when using original mod by megafuji

https://github.com/TheMegafuji/MegaAethric/assets/132860821/9d91565d-e83e-46c8-82f3-04fc3d113220

**Comment by Xray1716** [comment]
> Будьте осторожны, моя учетная запись была отключена при использовании новой версии этого мода.
> 
> Безопаснее использовать оригинальный мод от megafuji.
> 
> Я пытаюсь открыть приложение с оригинальной версией, но ничего не меняется
> 
>  Screen_Recording_20230607_073030_Aethric.mp4

I was blocked too. But that's okay. I'm already pumping a new PersianI was blocked too. But that's okay. I'm already pumping a new character
