### ISSUE TITLE
Continuation and auto-attack function.

### ISSUE THREAD

**Issue by Matvel007** [TheMegafuji/MegaAethric#4]
Why is it that when I'm fishing and an enemy comes across, the continue button does not work, just after defeating the enemy. The continue function is not implemented ? Also, when auto-attacking an enemy on the map, the attack button is not pressed automatically.

**Comment by TheMegafuji** [comment]
Just did the following and it works:
1. Activate Auto Continue
2. Remove mob bar
3. Activate Auto Battle
4. Cast a Fishing Line in Fishing Hut

Its auto fishing and when there is a battle, it automatically finish it.

I think you are talking about Auto-Attack inside battle, which is only available whilst Auto Battle is off, this is intentionally disabled after battle for allowing the player to make a decision, since it does exactly the same of Auto Battle, it works as a copilot to manual playing.

**Comment by Matvel007** [comment]
I talked about the green continue button and attacking the boss in the open world.  I found a way to make the functions work.  I play in Russian and the continuation functions do not work on it, only in English.

**Comment by TheMegafuji** [comment]
This is a very relevant comment indeed, its required to play the bot in english, or it won't work as intended.

**Comment by Matvel007** [comment]
I put the bot on Farm bosses and everything works perfectly.  That's just why the bot can just stop attacking bosses, you have to manually click on the icons of enemies.  What could be the problem ?  What's on the emulator and what's on the phone is the same.

**Comment by Matvel007** [comment]
I put the bot on Farm bosses and everything works perfectly.  That's just why the bot can just stop attacking bosses, you have to manually click on the icons of enemies.  What could be the problem ?  What's on the emulator and what's on the phone is the same.

**Comment by TheMegafuji** [comment]
The bot has an auto "wait" mode, it will only battle above 85% HP and 75% MP, I don't remember the exact values, but its something next to it, you need to have potions and auto heal active in order to continue farming non-stop, otherwise, it will only continue attacking after the HP has regenerated, if you also have auto gather on, perhaps you get a fountain and it will heal.
